import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { formatAud } from "@/lib/calculations";
import type { BasSummary } from "@/lib/types";
import { registerPdfFonts } from "./fonts";

registerPdfFonts();

const styles = StyleSheet.create({
  page: { padding: 42, fontFamily: "PaperMintSans", fontSize: 10, color: "#17211b" },
  brand: { color: "#2f8c67", fontWeight: 700, fontSize: 10, marginBottom: 10 },
  title: { fontSize: 24, fontWeight: 700 },
  subtitle: { marginTop: 6, color: "#66736b", lineHeight: 1.5 },
  section: { marginTop: 28 },
  sectionTitle: { fontSize: 12, fontWeight: 700, marginBottom: 8 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "#e4eae4" },
  label: { width: "70%", color: "#66736b" },
  value: { width: "30%", textAlign: "right", fontWeight: 700 },
  net: { marginTop: 18, flexDirection: "row", justifyContent: "space-between", padding: 14, backgroundColor: "#17211b", color: "#fff", fontSize: 13, fontWeight: 700 },
  note: { marginTop: 28, padding: 14, backgroundColor: "#f2f6f3", color: "#66736b", lineHeight: 1.55 },
  footer: { position: "absolute", bottom: 20, left: 42, right: 42, borderTopWidth: 1, borderTopColor: "#e4eae4", paddingTop: 7, textAlign: "center", color: "#879189", fontSize: 8 }
});

export function BasReportPdf({ companyName, summary }: { companyName: string; summary: BasSummary }) {
  return <Document title={`${companyName} BAS preparation summary`}><Page size="A4" style={styles.page}>
    <Text style={styles.brand}>PAPERMINT · BAS PREPARATION</Text>
    <Text style={styles.title}>{companyName || "All companies"}</Text>
    <Text style={styles.subtitle}>{summary.periodStart} to {summary.periodEnd} · {summary.accountingBasis === "cash" ? "Cash basis" : "Non-cash (accrual) basis"}</Text>
    <View style={styles.section}><Text style={styles.sectionTitle}>GST labels</Text>
      <ReportRow label="G1 Total sales (GST inclusive)" value={summary.g1TotalSales} />
      <ReportRow label="G10 Capital purchases" value={summary.g10CapitalPurchases} />
      <ReportRow label="G11 Non-capital purchases" value={summary.g11NonCapitalPurchases} />
      <ReportRow label="Trading stock purchases (included in G11)" value={summary.g11TradingStockPurchases} />
      <ReportRow label="1A GST on sales" value={summary.gstOnSales1A} />
      <ReportRow label="1B GST on purchases" value={summary.gstOnPurchases1B} />
    </View>
    <View style={styles.section}><Text style={styles.sectionTitle}>Returns and loss adjustments</Text>
      <ReportRow label="Paid-invoice return / loss value" value={summary.returnsLosses} />
      <ReportRow label="GST reduction included in 1A" value={summary.returnGstAdjustments} />
    </View>
    <View style={styles.net}><Text>Estimated net GST</Text><Text>{formatAud(summary.netGst)}</Text></View>
    <Text style={styles.note}>Preparation summary only. Review source documents, GST eligibility, adjustments, GST-free sales, exports, PAYG and any other BAS labels with your accountant or registered tax agent before lodging.</Text>
    <Text fixed style={styles.footer}>Generated by PaperMint · Review before lodgement</Text>
  </Page></Document>;
}

function ReportRow({ label, value }: { label: string; value: number }) {
  return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{formatAud(value)}</Text></View>;
}
